services:

  nginx:
    image: orthancteam/orthanc-nginx:24.9.1
    depends_on: [ orthanc, orthanc-auth-service, orthanc-for-api, meddream-viewer, keycloak ]
    restart: unless-stopped
    #    ports: ["8080:80"]
    # if setting ENABLE_HTTPS: "true" env var, uncomment the following 4 lines and comment the line with 'ports: ["80:80"]'
    ports: [ "443:443" ]
    volumes:
      - ../security/crt.pem:/etc/nginx/tls/crt.pem
      - ../security/key.pem:/etc/nginx/tls/key.pem
    environment:
      ENABLE_ORTHANC: "true"
      ENABLE_KEYCLOAK: "true"
      ENABLE_OHIF: "true"
      ENABLE_ORTHANC_TOKEN_SERVICE: "true"
      ENABLE_HTTPS: "true"
      ENABLE_MEDDREAM: "true"
      ENABLE_WSI: "true"
      ENABLE_ORTHANC_FOR_API: "true"

  orthanc:
    image: orthancteam/orthanc:24.10.3-full
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./custom.css:/home/custom/custom.css
      - ./images/logo.png:/home/custom/logo.png
      - ./images/favicon.ico:/home/custom/favicon.ico
      - ./customupload.lua:/etc/share/orthanc/scripts/customupload.lua

    depends_on: [ orthanc-db ]
    ports: [ "42421:4242", "80421:8042" ]
    restart: unless-stopped
    environment:
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__POSTGRESQL__HOST: "orthanc-db"
      ORTHANC__POSTGRESQL__ENABLE_INDEX: "true"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      HOUSEKEEPER_PLUGIN_ENABLED: "true"
      DELAYED_DELETION_PLUGIN_ENABLED: "true"
      NEURO_PLUGIN_ENABLED: "true"
      WSI_PLUGIN_ENABLED: "true"
      CONNECTIVITY_CHECKS_PLUGIN_ENABLED: "true"
      WORKLISTS_PLUGIN_ENABLED: "true"
      TCIA_PLUGIN_ENABLED: "true"
      ORTHANC__TCIA__URL: "https://pacs.mylabctg.com/orthanc/tcia/app/index.html"
      VOLVIEW_PLUGIN_ENABLED: "false"
      ORTHANC__PYTHON_VERBOSE: "true"
      ORTHANC__PYTHON_PLUGIN_ENABLED: "true"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
      ORTHANC__POSTGRESQL__INDEX_CONNECTIONS_COUNT: 10
      ORTHANC__POSTGRESQL__TRANSACTION_MODE: "ReadCommitted"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_SHARES: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__STUDY_LIST_SEARCH_MODE: "search-button"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__SHOW_SAME_PATIENT_STUDIES_FILTER: '["PatientBirthDate"]'

  orthanc-auth-service:
    image: orthancteam/orthanc-auth-service:24.9.1
    depends_on: [ keycloak, meddream-token-service ]
    # permissions can be customized in the permissions.json file
    volumes:
      - ./permissions.jsonc:/orthanc_auth_service/permissions.json
    restart: unless-stopped
    environment:
      SECRET_KEY: "change-me-I-am-a-secret-key"
      ENABLE_KEYCLOAK: "true"
      PUBLIC_ORTHANC_ROOT: "https://pacs.mylabctg.com/orthanc/"
      PUBLIC_LANDING_ROOT: "https://pacs.mylabctg.com/orthanc/ui/app/token-landing.html"
      USERS: |
        {
          "test": "test"
        }
      MEDDREAM_TOKEN_SERVICE_URL: "http://meddream-token-service:8088/v3/generate"
      PUBLIC_MEDDREAM_ROOT: "https://pacs.mylabctg.com/meddream/"
      PUBLIC_OHIF_ROOT: "https://pacs.mylabctg.com/ohif/"

  orthanc-db:
    image: postgres
    restart: unless-stopped
    volumes: [ "orthanc-db:/var/lib/postgresql/data" ]
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  keycloak:
    image: orthancteam/orthanc-keycloak:24.7.2
    depends_on: [ keycloak-db ]
    restart: unless-stopped
    volumes:
      - ../images/orthanc-bg.png:/opt/keycloak/themes/orthanc/login/resources/img/orthanc-bg.png
      - ../images/orthanc-logo.png:/opt/keycloak/themes/orthanc/login/resources/img/orthanc-logo.png
      - ../images/orthanc-logo-text.png:/opt/keycloak/themes/orthanc/login/resources/img/orthanc-logo-text.png
      - ../images/orthanc-logo-text-shadow.png:/opt/keycloak/themes/orthanc/login/resources/img/orthanc-logo-text-shadow.png
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "password"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://keycloak-db:5432/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "keycloak"
      KC_HOSTNAME_URL: "https://pacs.mylabctg.com/keycloak"
      KC_HOSTNAME_ADMIN_URL: "https://pacs.mylabctg.com/keycloak"

  keycloak-db:
    image: postgres
    restart: unless-stopped
    volumes: [ "keycloak-db:/var/lib/postgresql/data" ]
    environment:
      POSTGRES_PASSWORD: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_DB: "keycloak"

  meddream-token-service:
    image: orthancteam/meddream-token-service:24.9.1
    restart: unless-stopped

  ohif:
    image: orthancteam/ohif-v3:24.9.1
    #  customize ohif configuration applied
    volumes:
      - ./ohif-v3.js:/usr/share/nginx/html/app-config.js
    #      - ./ohif-logo.svg:/usr/share/nginx/html/ohif-logo.svg:ro
    #      - ./ohif-logo-light.svg:/usr/share/nginx/html/ohif-logo-light.svg:ro
    restart: unless-stopped

  meddream-viewer:
    image: orthancteam/meddream-viewer:24.9.1
    restart: unless-stopped
    depends_on:
      - orthanc-for-api
    environment:
      integration: "study"
      TOKEN_SERVICE_ADDRESS: "https://meddream-token-service:8088/v3/validate"
      ORTHANC_BASE_URL: "https://orthanc-for-api:8042"
      ORTHANC_USER: "meddream-user"
      ORTHANC_PWD: "change-me"
      ORTHANC_MEDDREAM_PYTHON_PLUGIN_ENABLED: "true"
      MEDDREAM_ADMIN_PASSWORD: "demo"
      MEDDREAM_PACS_CONFIG_TYPE: "Dicomweb"
      ORTHANC_HOSTNAME: "orthanc-for-api"
      ORTHANC_DICOM_PORT: 4242
      ORTHANC_AET: "SERVERMAIN1"
    volumes:
      - meddream-license:/opt/meddream/license

  # An orthanc dedicated for API accesses and also used by MedDream
  orthanc-for-api:
    image: orthancteam/orthanc:24.10.3-full
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      - ./meddream-plugin.py:/scripts/meddream-plugin.py
    depends_on: [ orthanc-db ]
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "Orthanc for API"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC__PYTHON_SCRIPT: "/scripts/meddream-plugin.py"
      ORTHANC__AUTHENTICATION_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__DICOM_WEB__PUBLIC_ROOT: "/orthanc-api/dicom-web/"
      ORTHANC__POSTGRESQL__HOST: "orthanc-db"
      ORTHANC_JSON: |
        {
          "RegisteredUsers": {
            "meddream-user": "change-me",
            "script-user": "change-me",
            "dicom-web-client-user": "change-me"
          }
        }

volumes:
  orthanc-storage:
  orthanc-db:
  keycloak-db:
  meddream-license:
